### ISSUE TITLE
Allow to config multiple contexts

### ISSUE THREAD

**Issue by sljricardo** [2phost/octoforward#2]
Allow to configure different contexts for each conection, eg:

```yaml
groups:
  - name: staging
    services:
      - displayName: Elasticsearch
        context: name-of-context-1
        port: 9200
        servicePort: 9200
        namespace: eck
        name: es-es-http
        protocol: http
      - displayName: Kibana
        context: name-of-context-2
        port: 5601
        servicePort: 5601
        namespace: eck
        name: kibana-kb-http
        protocol: http
```

if not define should use the default context
