### ISSUE TITLE
Allow to setup Pods

### ISSUE THREAD

**Issue by sljricardo** [2phost/octoforward#3]
Allow to configure PODs eg:

```yaml
groups:
  - name: staging
    services:
      - displayName: Elasticsearch
        port: 9200
        servicePort: 9200
        namespace: eck
        name: es-es-http
        protocol: http
    pod:
      - displayName: Kibana-pod
        port: 5601
        servicePort: 5601
        namespace: eck
        name: kibana-kb-87df576fd-whhmt
        protocol: http
```
